name       : soqt
version    : 1.6.0
release    : 1
source     :
    - https://github.com/coin3d/soqt/releases/download/SoQt-1.6.0/soqt-1.6.0-src.tar.gz : 9f535af59f07c907022815679681bd345c9dec2f408c74833f6b1b24bca40e1f
    - https://github.com/coin3d/soanydata/archive/refs/tags/soanydata-1_1_0.tar.gz : 203de840b99b3641ab27462be9d493a63d2bc9f03530ae58230f2e848e9ce25b
    - https://github.com/coin3d/sogui/archive/refs/tags/soxt-1_4_0.tar.gz : e863e83240b7213cb6aa15fde15cf9cd8290732bfc90c70110b957533a9ccc60
license    : BSD-3-Clause
component  : programming.library
summary    : Glue between Coin and Qt
description: |
    SoQt is a Qt GUI component toolkit library for Coin.
builddeps  :
    - pkgconfig(Coin)
    - pkgconfig(Qt5Core)
    - pkgconfig(xi)
    - doxygen
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    rm -rf {data,soqt/src/Inventor/Qt/common}
    mkdir -p {data,soqt/src/Inventor/Qt/common}
    tar xf $sources/soanydata-* --strip-components=1 -C data
    tar xf $sources/soxt-* --strip-components=1 -C soqt/src/Inventor/Qt/common
    %cmake_ninja \
        -DSOQT_BUILD_DOCUMENTATION=ON \
        -DSOQT_BUILD_DOC_MAN=ON \
        -DSOQT_BUILD_DOC_CHM=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
    cd $installdir/usr/share/man/man3
    for low in [a-z]*.3; do
        mv $low SoQt_$low
    done
